# Generated by Django 3.1 on 2020-12-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=60)),
                ('year', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('star_cast', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
            ],
        ),
    ]
